### ISSUE TITLE
Add an about page

### ISSUE THREAD

**Issue by bsautermeister** [pfent/Android-MISL-Control#7]
Add an **AboutActivity** to show some information about the app:
- Logo
- Version
- Developer names
- Android Practical course
- TAMU/TUM coorp
- Project information
- License information
- ...

**Comment by bsautermeister** [comment]
An empty about activity was added. The about page can be accessed via the settings page.

**Comment by pfent** [comment]
about page added as an PreferenceFragment.
we still need to gather information about the various software licenses in use
