### ISSUE TITLE
Implement the Settings Page

### ISSUE THREAD

**Issue by bsautermeister** [pfent/Android-MISL-Control#8]
Implement the **SettingsActivity**, to do at least the following:
- Select control type (joystick, sensor)
- Network setup (IP, Port, SSID?)

**Comment by bsautermeister** [comment]
Startet to implement the settings page. The auto generated code of the template was complete removed (because it uses deprecated code). From now on, we use PreferenceFragments.

Currently, the control type selection is implemented only. Other sections are currently empty, but already defined.

**Comment by pfent** [comment]
Settings page is implemented, we just need to respect the values set there
